IntruderDetection:
	g++ -g main.cpp -lopencv_highgui -lopencv_core -lopencv_video -lopencv_videoio -lopencv_imgproc -lopencv_imgcodecs -L/usr/local/Cellar/ffmpeg/4.0/lib -lavcodec -lavformat -lavutil -lswscale -o IntruderDetection
